/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Restaurant extends Business {

    private int price;

    public Restaurant(String name, int price) {
        super(name);
        this.setStars(0);
        this.price = price;
    }

    public int getPrice() {
        return price;
    }

    @Override
    public String toString() {
        return "Restaurant " +
                "name: '" + this.getName() + '\'' +
                ", stars: " + this.getStars() +
                ", price: " + price;
    }
}
