/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;
import java.util.List;

public class Restaurant {
    private String name;
    private int stars;
    private int price;
    private static int totalStars;
    private static List<Review> reviewList = new ArrayList<>();

    public Restaurant(String name, int price) {
        this.name = name;
        this.stars = 0;
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public int getStars() {
        return stars;
    }

    public int getPrice() {
        return price;
    }

    public void addReview(Review review) {
        reviewList.add(review);
        totalStars += review.getStars();
        stars = totalStars/(reviewList.size());
    }

    @Override
    public String toString() {
        return "Restaurant " +
                "name: '" + name + '\'' +
                ", stars: " + stars +
                ", price: " + price;
    }
}
