/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(readFile("src/main/resources/gates.js"));

    }

    public static String readFile(String filepath) {
        StringBuilder errorList = new StringBuilder();
        int addCount = 0;

        try {
            Scanner scanner = new Scanner(new File(filepath));
            int lineCount = 0;
            while(scanner.hasNext()) {
                lineCount++;
                String nextLine = scanner.nextLine();
                //logic / conditionals
                if(!(nextLine.isEmpty() || nextLine.endsWith("{") || nextLine.endsWith("}") || nextLine.contains("if")
                        || nextLine.contains("else")) && !nextLine.endsWith(";")) {
                    errorList.append("\nLine " + lineCount + ": Missing Semicolon.");
                    addCount++;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        //test that there are 46 errors for file
        System.out.println("Number of errors: " + addCount);
        return errorList.toString();

    }

}
